################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../application_properties.c \
../bsp_trace.c \
../custom_adv.c \
../eeprom_emulation.c \
../gatt_db.c \
../init_app.c \
../init_board.c \
../init_mcu.c \
../interrupt.c \
../main.c 

OBJS += \
./application_properties.o \
./bsp_trace.o \
./custom_adv.o \
./eeprom_emulation.o \
./gatt_db.o \
./init_app.o \
./init_board.o \
./init_mcu.o \
./interrupt.o \
./main.o 

C_DEPS += \
./application_properties.d \
./bsp_trace.d \
./custom_adv.d \
./eeprom_emulation.d \
./gatt_db.d \
./init_app.d \
./init_board.d \
./init_mcu.d \
./interrupt.d \
./main.d 


# Each subdirectory must supply rules for building sources it contributes
application_properties.o: ../application_properties.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-DRETARGET_VCOM=1' '-D__STACK_SIZE=0x800' '-DEFR32BG1B132F256GM32=1' -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\halconfig\inc\hal-config" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\uartdrv\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\bootloader\api" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\drivers" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\radio\rail_lib\common" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\tempdrv\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\sleep\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\common\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\sleep\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emlib\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\radio\rail_lib\chip\efr32" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emlib\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\bootloader" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\CMSIS\Include" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\tempdrv\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\bsp" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\halconfig" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"application_properties.d" -MT"application_properties.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

bsp_trace.o: ../bsp_trace.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-DRETARGET_VCOM=1' '-D__STACK_SIZE=0x800' '-DEFR32BG1B132F256GM32=1' -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\halconfig\inc\hal-config" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\uartdrv\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\bootloader\api" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\drivers" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\radio\rail_lib\common" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\tempdrv\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\sleep\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\common\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\sleep\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emlib\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\radio\rail_lib\chip\efr32" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emlib\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\bootloader" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\CMSIS\Include" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\tempdrv\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\bsp" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\halconfig" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"bsp_trace.d" -MT"bsp_trace.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

custom_adv.o: ../custom_adv.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-DRETARGET_VCOM=1' '-D__STACK_SIZE=0x800' '-DEFR32BG1B132F256GM32=1' -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\halconfig\inc\hal-config" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\uartdrv\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\bootloader\api" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\drivers" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\radio\rail_lib\common" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\tempdrv\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\sleep\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\common\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\sleep\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emlib\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\radio\rail_lib\chip\efr32" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emlib\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\bootloader" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\CMSIS\Include" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\tempdrv\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\bsp" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\halconfig" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"custom_adv.d" -MT"custom_adv.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

eeprom_emulation.o: ../eeprom_emulation.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-DRETARGET_VCOM=1' '-D__STACK_SIZE=0x800' '-DEFR32BG1B132F256GM32=1' -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\halconfig\inc\hal-config" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\uartdrv\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\bootloader\api" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\drivers" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\radio\rail_lib\common" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\tempdrv\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\sleep\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\common\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\sleep\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emlib\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\radio\rail_lib\chip\efr32" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emlib\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\bootloader" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\CMSIS\Include" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\tempdrv\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\bsp" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\halconfig" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"eeprom_emulation.d" -MT"eeprom_emulation.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gatt_db.o: ../gatt_db.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-DRETARGET_VCOM=1' '-D__STACK_SIZE=0x800' '-DEFR32BG1B132F256GM32=1' -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\halconfig\inc\hal-config" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\uartdrv\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\bootloader\api" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\drivers" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\radio\rail_lib\common" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\tempdrv\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\sleep\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\common\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\sleep\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emlib\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\radio\rail_lib\chip\efr32" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emlib\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\bootloader" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\CMSIS\Include" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\tempdrv\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\bsp" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\halconfig" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"gatt_db.d" -MT"gatt_db.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

init_app.o: ../init_app.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-DRETARGET_VCOM=1' '-D__STACK_SIZE=0x800' '-DEFR32BG1B132F256GM32=1' -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\halconfig\inc\hal-config" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\uartdrv\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\bootloader\api" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\drivers" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\radio\rail_lib\common" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\tempdrv\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\sleep\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\common\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\sleep\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emlib\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\radio\rail_lib\chip\efr32" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emlib\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\bootloader" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\CMSIS\Include" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\tempdrv\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\bsp" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\halconfig" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"init_app.d" -MT"init_app.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

init_board.o: ../init_board.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-DRETARGET_VCOM=1' '-D__STACK_SIZE=0x800' '-DEFR32BG1B132F256GM32=1' -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\halconfig\inc\hal-config" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\uartdrv\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\bootloader\api" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\drivers" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\radio\rail_lib\common" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\tempdrv\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\sleep\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\common\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\sleep\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emlib\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\radio\rail_lib\chip\efr32" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emlib\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\bootloader" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\CMSIS\Include" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\tempdrv\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\bsp" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\halconfig" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"init_board.d" -MT"init_board.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

init_mcu.o: ../init_mcu.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-DRETARGET_VCOM=1' '-D__STACK_SIZE=0x800' '-DEFR32BG1B132F256GM32=1' -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\halconfig\inc\hal-config" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\uartdrv\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\bootloader\api" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\drivers" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\radio\rail_lib\common" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\tempdrv\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\sleep\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\common\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\sleep\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emlib\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\radio\rail_lib\chip\efr32" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emlib\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\bootloader" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\CMSIS\Include" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\tempdrv\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\bsp" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\halconfig" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"init_mcu.d" -MT"init_mcu.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

interrupt.o: ../interrupt.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-DRETARGET_VCOM=1' '-D__STACK_SIZE=0x800' '-DEFR32BG1B132F256GM32=1' -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\halconfig\inc\hal-config" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\uartdrv\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\bootloader\api" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\drivers" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\radio\rail_lib\common" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\tempdrv\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\sleep\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\common\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\sleep\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emlib\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\radio\rail_lib\chip\efr32" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emlib\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\bootloader" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\CMSIS\Include" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\tempdrv\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\bsp" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\halconfig" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"interrupt.d" -MT"interrupt.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

main.o: ../main.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-DRETARGET_VCOM=1' '-D__STACK_SIZE=0x800' '-DEFR32BG1B132F256GM32=1' -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\halconfig\inc\hal-config" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\uartdrv\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\bootloader\api" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\drivers" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\radio\rail_lib\common" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\tempdrv\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\sleep\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\common\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\sleep\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emlib\src" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\radio\rail_lib\chip\efr32" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emlib\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\bootloader" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\CMSIS\Include" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\tempdrv\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\bsp" -I"C:\Users\bruno\SimplicityStudio\v4_workspace\botao_panico_custom_board\hardware\kit\common\halconfig" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"main.d" -MT"main.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


